#include "Main.h"

#include "System.cpp"
#include "Image.cpp"
#include "Font.cpp"
#include "Sound.cpp"
#include "Animation.cpp"
#include "Background.cpp"
#include "Creature.cpp"
#include "Cloud.cpp"
#include "Spawner.cpp"
#include "Collider.cpp"
#include "Timer.cpp"
#include "Menu.cpp"
#include "Game.cpp"
#include "Error.cpp"
#include "Platform.cpp"
